# fitz_sage/cli/commands/init_config.py
"""
Config generation for init wizard.

Pure functions that generate YAML configuration strings.
"""

from __future__ import annotations


def generate_global_config(default_engine: str) -> str:
    """Generate the global config YAML with just default_engine."""
    return f"""# Fitz Global Configuration
# Generated by: fitz init

# Default engine for CLI commands
default_engine: {default_engine}
"""


def _build_vdb_kwargs_section(vector_db: str) -> str:
    """Build vector_db_kwargs YAML section."""
    if vector_db == "pgvector":
        return """
# Vector DB kwargs (pgvector settings)
vector_db_kwargs:
  mode: local  # "local" (embedded) or "external" (connection_string)"""
    return ""


def _build_chat_specs(
    chat: str,
    chat_model_smart: str,
    chat_model_fast: str,
    chat_model_balanced: str,
) -> str:
    """Build chat tier spec lines."""

    def _spec(model: str) -> str:
        if model:
            return f"{chat}/{model}"
        return chat

    return f"""chat_fast: {_spec(chat_model_fast)}
chat_balanced: {_spec(chat_model_balanced)}
chat_smart: {_spec(chat_model_smart)}"""


def _build_embedding_spec(embedding: str, embedding_model: str) -> str:
    """Build embedding spec line."""
    if embedding_model:
        return f"embedding: {embedding}/{embedding_model}"
    return f"embedding: {embedding}"


def _build_rerank_line(rerank: str | None, rerank_model: str) -> str:
    """Build rerank line."""
    if rerank:
        if rerank_model:
            return f"rerank: {rerank}/{rerank_model}"
        return f"rerank: {rerank}"
    return "rerank: null  # No reranker configured"


def _build_vision_line(vision: str | None, vision_model: str) -> str:
    """Build vision line."""
    if vision:
        if vision_model:
            return f"vision: {vision}/{vision_model}"
        return f"vision: {vision}"
    return "vision: null  # Enable with: vision: openai/gpt-4o or vision: ollama/llava"


def generate_fitz_krag_config(
    *,
    chat: str,
    chat_model_smart: str,
    chat_model_fast: str,
    chat_model_balanced: str = "",
    embedding: str,
    embedding_model: str,
    rerank: str | None,
    rerank_model: str,
    vector_db: str,
    vision: str | None = None,
    vision_model: str = "",
) -> str:
    """
    Generate the Fitz KRAG config YAML string.

    Produces flat YAML with provider/model specs for each tier.
    """
    chat_specs = _build_chat_specs(chat, chat_model_smart, chat_model_fast, chat_model_balanced)
    embedding_spec = _build_embedding_spec(embedding, embedding_model)
    rerank_line = _build_rerank_line(rerank, rerank_model)
    vision_line = _build_vision_line(vision, vision_model)
    vdb_kwargs_section = _build_vdb_kwargs_section(vector_db)

    return f"""# Fitz KRAG Engine Configuration
# Generated by: fitz init
#
# KRAG = Knowledge Routing Augmented Generation
# Uses knowledge-type-aware strategies instead of uniform chunk retrieval.

# ===========================================================================
# Chat models by tier (provider/model)
# ===========================================================================

{chat_specs}

# ===========================================================================
# Embedding model
# ===========================================================================

{embedding_spec}

# ===========================================================================
# Vector database
# ===========================================================================

vector_db: {vector_db}

# ===========================================================================
# Optional Features (null = disabled)
# ===========================================================================

{rerank_line}
{vision_line}

# ===========================================================================
# Collection
# ===========================================================================

collection: default

# ===========================================================================
# Code Strategy
# ===========================================================================

code_languages: [python, typescript, java, go]
summary_batch_size: 15
max_expansion_depth: 1
include_class_context: true

# ===========================================================================
# Retrieval
# ===========================================================================

top_addresses: 10
top_read: 5
keyword_weight: 0.4
semantic_weight: 0.6
fallback_to_chunks: true
section_bm25_weight: 0.6
section_semantic_weight: 0.4

# ===========================================================================
# Context Assembly
# ===========================================================================

max_context_tokens: 8000
include_file_header: true

# ===========================================================================
# Generation
# ===========================================================================

enable_citations: true
strict_grounding: true

# ===========================================================================
# Logging
# ===========================================================================

log_level: INFO
{vdb_kwargs_section}
"""


def copy_engine_default_config(engine_name: str, registry) -> str | None:
    """
    Get the content of an engine's default config file.

    Uses the registry to discover the engine's default config path,
    then reads and returns its contents.

    Args:
        engine_name: Name of the engine
        registry: The engine registry instance

    Returns:
        Config file contents as string, or None if no default config
    """
    default_path = registry.get_default_config_path(engine_name)
    if default_path is None or not default_path.exists():
        return None

    return default_path.read_text(encoding="utf-8")
