# fitz_ai/cli/commands/init.py
"""
Interactive setup wizard for Fitz.

Usage:
    fitz init              # Interactive wizard
    fitz init -y           # Auto-detect and use defaults
    fitz init --show       # Preview config without saving
"""

from __future__ import annotations

from typing import Any

import typer

from fitz_ai.core.detect import detect_all
from fitz_ai.llm.registry import available_llm_plugins
from fitz_ai.llm.loader import load_plugin
from fitz_ai.vector_db.registry import available_vector_db_plugins
from fitz_ai.cli.ui import ui, console, RICH


# =============================================================================
# Helpers
# =============================================================================


def _is_local_plugin(name: str) -> bool:
    """Check if plugin is local/Ollama-based."""
    return any(x in name.lower() for x in ("ollama", "local", "offline"))


def _is_faiss_plugin(name: str) -> bool:
    """Check if plugin is FAISS-based."""
    return "faiss" in name.lower()


def _auto_or_prompt(category: str, available: list[str], default: str, prompt: str) -> str:
    """Auto-select if one option, otherwise prompt."""
    if len(available) == 1:
        choice = available[0]
        if RICH:
            console.print(f"  [dim]{category}:[/dim] [green]{choice}[/green] [dim](auto)[/dim]")
        else:
            print(f"  {category}: {choice} (auto)")
        return choice
    return ui.prompt_choice(prompt, available, default)


def _get_default_model(plugin_type: str, plugin_name: str) -> str:
    """Get default model from YAML plugin spec."""
    try:
        spec = load_plugin(plugin_type, plugin_name)
        return spec.defaults.get("model", "")
    except Exception:
        return ""


def _prompt_model(plugin_type: str, plugin_name: str) -> str:
    """Prompt for model with default from YAML plugin."""
    default = _get_default_model(plugin_type, plugin_name)
    if not default:
        return ""  # No model config for this plugin

    return ui.prompt_text(f"  {plugin_type.capitalize()} model", default)


# =============================================================================
# Plugin Filtering
# =============================================================================


def _filter_available_plugins(
        plugins: list[str],
        plugin_type: str,
        system: Any,
) -> list[str]:
    """Filter plugins to only those that are available."""
    available = []

    for plugin in plugins:
        is_available = False

        # Check local/Ollama plugins
        if _is_local_plugin(plugin):
            is_available = system.ollama.available

        # Check FAISS
        elif _is_faiss_plugin(plugin):
            is_available = system.faiss.available

        # Check Qdrant
        elif plugin == "qdrant":
            is_available = system.qdrant.available

        # Check API key providers
        elif plugin in system.api_keys:
            is_available = system.api_keys[plugin].available

        if is_available:
            available.append(plugin)

    return available


# =============================================================================
# Config Generation
# =============================================================================


def _generate_config(
        chat: str,
        chat_model: str,
        embedding: str,
        embedding_model: str,
        vector_db: str,
        collection: str,
        rerank: str | None,
        rerank_model: str,
        qdrant_host: str,
        qdrant_port: int,
) -> str:
    """Generate YAML configuration."""

    # Chat kwargs
    chat_kwargs = "\n    temperature: 0.2"
    if chat_model:
        chat_kwargs = f"\n    model: {chat_model}\n    temperature: 0.2"

    # Embedding kwargs
    embedding_kwargs = " {}"
    if embedding_model:
        embedding_kwargs = f"\n    model: {embedding_model}"

    # Vector DB kwargs
    vdb_kwargs = ""
    if vector_db == "qdrant":
        vdb_kwargs = f"""
    host: "{qdrant_host}"
    port: {qdrant_port}"""

    # Rerank section
    if rerank:
        rerank_kwargs = " {}"
        if rerank_model:
            rerank_kwargs = f"\n    model: {rerank_model}"
        rerank_section = f"""
# Reranker (improves retrieval quality)
rerank:
  enabled: true
  plugin_name: {rerank}
  kwargs:{rerank_kwargs}
"""
    else:
        rerank_section = """
# Reranker (disabled)
rerank:
  enabled: false
"""

    return f"""# Fitz RAG Configuration
# Generated by: fitz init

# Chat (LLM for answering questions)
chat:
  plugin_name: {chat}
  kwargs:{chat_kwargs}

# Embedding (text to vectors)
embedding:
  plugin_name: {embedding}
  kwargs:{embedding_kwargs}

# Vector Database
vector_db:
  plugin_name: {vector_db}
  kwargs:{vdb_kwargs if vdb_kwargs else " {}"}

# Retriever
retriever:
  plugin_name: dense
  collection: {collection}
  top_k: 5
{rerank_section}
# RGS (Retrieval-Guided Synthesis)
rgs:
  enable_citations: true
  strict_grounding: true
  max_chunks: 8

# Logging
logging:
  level: INFO
"""


# =============================================================================
# Main Command
# =============================================================================


def command(
        non_interactive: bool = typer.Option(
            False,
            "--non-interactive",
            "-y",
            help="Use detected defaults without prompting.",
        ),
        show_config: bool = typer.Option(
            False,
            "--show",
            "-s",
            help="Preview config without saving.",
        ),
) -> None:
    """
    Initialize Fitz with an interactive setup wizard.

    Detects available providers (API keys, Ollama, Qdrant) and
    creates a working configuration file.

    Examples:
        fitz init           # Interactive wizard
        fitz init -y        # Auto-detect and use defaults
        fitz init --show    # Preview config without saving
    """
    from fitz_ai.core.paths import FitzPaths

    # =========================================================================
    # Header
    # =========================================================================

    ui.panel(
        "[bold]Fitz Setup Wizard[/bold]\n[dim]Let's configure your RAG pipeline[/dim]" if RICH else "Fitz Setup Wizard\nLet's configure your RAG pipeline",
        style="blue",
    )

    # =========================================================================
    # Detect System
    # =========================================================================

    ui.section("Detecting System")

    system = detect_all()

    # Show detection results
    ui.status("Ollama", system.ollama.available, system.ollama.details if not system.ollama.available else "")
    ui.status("Qdrant", system.qdrant.available,
              f"{system.qdrant.host}:{system.qdrant.port}" if system.qdrant.available else "")
    ui.status("FAISS", system.faiss.available)

    for name, key_status in system.api_keys.items():
        ui.status(name.capitalize(), key_status.available)

    # =========================================================================
    # Discover Plugins
    # =========================================================================

    all_chat = available_llm_plugins("chat")
    all_embedding = available_llm_plugins("embedding")
    all_rerank = available_llm_plugins("rerank")
    all_vector_db = available_vector_db_plugins()

    # Filter to available only
    avail_chat = _filter_available_plugins(all_chat, "chat", system)
    avail_embedding = _filter_available_plugins(all_embedding, "embedding", system)
    avail_rerank = _filter_available_plugins(all_rerank, "rerank", system)
    avail_vector_db = _filter_available_plugins(all_vector_db, "vector_db", system)

    # =========================================================================
    # Validate Minimum Requirements
    # =========================================================================

    if not avail_chat:
        ui.error("No chat plugins available!")
        ui.info("Set an API key (COHERE_API_KEY, OPENAI_API_KEY) or start Ollama.")
        raise typer.Exit(1)

    if not avail_embedding:
        ui.error("No embedding plugins available!")
        raise typer.Exit(1)

    if not avail_vector_db:
        ui.error("No vector database available!")
        ui.info("Install FAISS (pip install faiss-cpu) or start Qdrant.")
        raise typer.Exit(1)

    # =========================================================================
    # User Selection
    # =========================================================================

    ui.section("Configuration")

    if non_interactive:
        # Use first available for each with defaults from YAML
        chat_choice = avail_chat[0]
        chat_model = _get_default_model("chat", chat_choice)
        embedding_choice = avail_embedding[0]
        embedding_model = _get_default_model("embedding", embedding_choice)
        vector_db_choice = avail_vector_db[0]
        rerank_choice = avail_rerank[0] if avail_rerank else None
        rerank_model = _get_default_model("rerank", rerank_choice) if rerank_choice else ""
        collection_name = "default"

        ui.info(f"Chat: {chat_choice}" + (f" ({chat_model})" if chat_model else ""))
        ui.info(f"Embedding: {embedding_choice}" + (f" ({embedding_model})" if embedding_model else ""))
        ui.info(f"Vector DB: {vector_db_choice}")
        ui.info(f"Rerank: {rerank_choice or 'disabled'}" + (f" ({rerank_model})" if rerank_model else ""))
        ui.info(f"Collection: {collection_name}")
    else:
        # Interactive selection

        # Chat plugin + model
        chat_choice = _auto_or_prompt("Chat", avail_chat, avail_chat[0], "Select chat plugin")
        chat_model = _prompt_model("chat", chat_choice)

        # Embedding plugin + model
        embedding_choice = _auto_or_prompt("Embedding", avail_embedding, avail_embedding[0], "Select embedding plugin")
        embedding_model = _prompt_model("embedding", embedding_choice)

        # Vector DB
        vector_db_choice = _auto_or_prompt("Vector DB", avail_vector_db, avail_vector_db[0], "Select vector database")

        # Rerank is optional
        rerank_choice = None
        rerank_model = ""
        if avail_rerank:
            if ui.prompt_confirm("Enable reranking?", default=True):
                rerank_choice = _auto_or_prompt("Rerank", avail_rerank, avail_rerank[0], "Select rerank plugin")
                rerank_model = _prompt_model("rerank", rerank_choice)
        else:
            ui.info("Rerank: not available")

        collection_name = ui.prompt_text("Collection name", "default")

    # =========================================================================
    # Generate Config
    # =========================================================================

    qdrant_host = system.qdrant.host if system.qdrant.available else "localhost"
    qdrant_port = system.qdrant.port if system.qdrant.available else 6333

    config_yaml = _generate_config(
        chat=chat_choice,
        chat_model=chat_model,
        embedding=embedding_choice,
        embedding_model=embedding_model,
        vector_db=vector_db_choice,
        collection=collection_name,
        rerank=rerank_choice,
        rerank_model=rerank_model,
        qdrant_host=qdrant_host,
        qdrant_port=qdrant_port,
    )

    # =========================================================================
    # Show Config
    # =========================================================================

    ui.section("Generated Configuration")
    ui.syntax(config_yaml, "yaml")

    if show_config:
        return

    # =========================================================================
    # Save Config
    # =========================================================================

    ui.section("Saving")

    fitz_dir = FitzPaths.workspace()
    fitz_config = FitzPaths.config()

    # Confirm overwrite if exists
    if fitz_config.exists() and not non_interactive:
        if not ui.prompt_confirm("Config exists. Overwrite?", default=False):
            ui.warning("Aborted.")
            raise typer.Exit(0)

    fitz_dir.mkdir(parents=True, exist_ok=True)
    fitz_config.write_text(config_yaml)
    ui.success(f"Saved to {fitz_config}")

    # =========================================================================
    # Next Steps
    # =========================================================================

    ui.section("Done!")

    if RICH:
        console.print(f"""
[green]Your configuration is ready![/green]

Next steps:
  [cyan]fitz ingest ./docs {collection_name}[/cyan]  # Ingest documents
  [cyan]fitz query "your question"[/cyan]           # Query knowledge base
  [cyan]fitz doctor[/cyan]                          # Verify setup
""")
    else:
        print(f"""
Your configuration is ready!

Next steps:
  fitz ingest ./docs {collection_name}  # Ingest documents
  fitz query "your question"            # Query knowledge base
  fitz doctor                           # Verify setup
""")