# fitz_ai/cli/commands/init_config.py
"""
Config generation for init wizard.

Pure functions that generate YAML configuration strings.
"""

from __future__ import annotations


def generate_global_config(default_engine: str) -> str:
    """Generate the global config YAML with just default_engine."""
    return f"""# Fitz Global Configuration
# Generated by: fitz init

# Default engine for CLI commands
default_engine: {default_engine}
"""


def generate_fitz_rag_config(
    *,
    chat: str,
    chat_model_smart: str,
    chat_model_fast: str,
    chat_model_balanced: str = "",
    embedding: str,
    embedding_model: str,
    rerank: str | None,
    rerank_model: str,
    vector_db: str,
    retrieval: str,
    chunker: str,
    chunk_size: int,
    chunk_overlap: int,
    parser: str = "docling",
    vision: str | None = None,
    vision_model: str = "",
) -> str:
    """
    Generate the Fitz RAG config YAML string.

    Uses the simplified schema format:
    - Plugins are strings: "provider" or "provider/model"
    - Plugin kwargs use separate _kwargs fields
    - None = disabled (no enabled flags)
    """
    # Build chat_kwargs section
    chat_kwargs_lines = []
    if chat_model_smart or chat_model_fast or chat_model_balanced:
        chat_kwargs_lines.append("  models:")
        if chat_model_smart:
            chat_kwargs_lines.append(f"    smart: {chat_model_smart}")
        if chat_model_fast:
            chat_kwargs_lines.append(f"    fast: {chat_model_fast}")
        if chat_model_balanced:
            chat_kwargs_lines.append(f"    balanced: {chat_model_balanced}")
    chat_kwargs_lines.append("  temperature: 0.2")
    chat_kwargs_section = "\n".join(chat_kwargs_lines)

    # Build embedding_kwargs section
    embedding_kwargs_section = ""
    if embedding_model:
        embedding_kwargs_section = f"  model: {embedding_model}"

    # Build rerank section
    if rerank:
        rerank_line = f"rerank: {rerank}"
        if rerank_model:
            rerank_kwargs_section = f"""
# Reranker kwargs
rerank_kwargs:
  model: {rerank_model}"""
        else:
            rerank_kwargs_section = ""
    else:
        rerank_line = "rerank: null  # No reranker configured"
        rerank_kwargs_section = ""

    # Build vision section
    if vision:
        vision_line = f"vision: {vision}"
        if vision_model:
            vision_kwargs_section = f"""
# Vision kwargs
vision_kwargs:
  model: {vision_model}"""
        else:
            vision_kwargs_section = ""
    else:
        vision_line = "vision: null  # Enable with: vision: openai or vision: anthropic"
        vision_kwargs_section = ""

    # Build vector_db_kwargs section
    vdb_kwargs_section = ""
    if vector_db == "pgvector":
        vdb_kwargs_section = """
# Vector DB kwargs (pgvector settings)
vector_db_kwargs:
  mode: local  # "local" (embedded) or "external" (connection_string)"""

    return f"""# Fitz RAG Engine Configuration
# Generated by: fitz init
#
# Plugin format: "provider" or "provider/model"
# Example: chat: anthropic/claude-sonnet-4

# ===========================================================================
# Core Plugins
# ===========================================================================

# Chat LLM for answering questions
chat: {chat}

# Embedding model for vectors
embedding: {embedding}

# Vector database
vector_db: {vector_db}

# ===========================================================================
# Optional Features (null = disabled)
# ===========================================================================

# Reranker for improved retrieval quality
{rerank_line}

# Vision/VLM for image parsing in PDFs
{vision_line}

# ===========================================================================
# Retrieval Settings
# ===========================================================================

retrieval_plugin: {retrieval}
collection: default
top_k: 5

# ===========================================================================
# Generation Settings
# ===========================================================================

enable_citations: true
strict_grounding: true
max_chunks: 8

# ===========================================================================
# Chunking Settings
# ===========================================================================

chunk_size: {chunk_size}
chunk_overlap: {chunk_overlap}
parser: {parser}

# ===========================================================================
# Logging
# ===========================================================================

log_level: INFO

# ===========================================================================
# Plugin Kwargs (Advanced)
# ===========================================================================

# Chat model tiers (smart for queries, fast for background tasks)
chat_kwargs:
{chat_kwargs_section}

# Embedding model override
embedding_kwargs:
{embedding_kwargs_section if embedding_kwargs_section else "  {}"}
{rerank_kwargs_section}{vision_kwargs_section}{vdb_kwargs_section}
"""


def copy_engine_default_config(engine_name: str, registry) -> str | None:
    """
    Get the content of an engine's default config file.

    Uses the registry to discover the engine's default config path,
    then reads and returns its contents.

    Args:
        engine_name: Name of the engine
        registry: The engine registry instance

    Returns:
        Config file contents as string, or None if no default config
    """
    default_path = registry.get_default_config_path(engine_name)
    if default_path is None or not default_path.exists():
        return None

    return default_path.read_text(encoding="utf-8")
